---
- name: "Create global group"
  ansible.builtin.group:
    name: "{{ profile_group }}"
    state: present

- name: "Create personal user"
  ansible.builtin.user:
    name: "{{ profile_name }}"
    shell: "{{ profile_user_shell }}"
    groups: "{{ profile_group }}"
    append: true
    password: "{{ profile_password | password_hash('sha512') }}"
    update_password: on_create
  when: profile_password is defined

- name: "Enable includedir parameter in sudoers"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^[@#]?includedir /etc/sudoers.d'
    line: '@includedir /etc/sudoers.d'
    validate: /usr/sbin/visudo -cf %s

- name: "Add sudoers drop-in file for the group"
  ansible.builtin.template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/10-admins.conf"
    owner: "root"
    group: "root"
    mode: "0440"
    validate: /usr/sbin/visudo -csf %s

- name: "Add SSH key to authorized_keys"
  ansible.posix.authorized_key:
    user: "{{ profile_name }}"
    key: "{{ profile_key }}"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ profile_packages }}"
